### ISSUE TITLE
Docker container help

### ISSUE THREAD

**Issue by SinisterSpatula** [DSJAS/DSJAS#14]
What causes this error please?  
```
DSJAS       | [Fri May 07 23:42:16.952767 2021] [php7:warn] [pid 18] [client 172.20.0.1:56730] PHP Warning:  require_once(vendor/hooks/src/gburtini/Hooks/Hooks.php): failed to open stream: No such file or directory in /var/www/html/include/Module.php on line 22
```
This happens to me when trying to build and run both the normal docker container and the .developer container.  Also happened to me a lot when trying to set this up on XAMPP.

Currently I'm using WSL (windows linux subsystem) with Debian distro.  I have Docker Desktop setup and working, it's able to build the containers (server and database) but after it's done and I browse to localhost the page is blank and I get the above error in the console.

What is the best way to build and run this if I want to try developing modules and themes under windows 10 using visual studio code?  There must be something that I'm just not understanding.  Seems like something is wrong with the php.ini somehow?  But I didn't edit or modify anything.  I did fork the project but I'm not even cloning from my fork, I'm cloning from the official repo and still getting stuck.

**Update: I just realized something, the file is literally missing.  For some strange reason when I clone the repo this happens, but if I download the release.zip and then build the containers I think those files are present.**  Maybe I have to run a Build or Package script after cloning the repo to get those additional files?

**Update: I just saw in the packager script that I should be using the recursive flag when I clone.  Oops :D  I think I figured it out. Sorry to bother.

**Comment by SinisterSpatula** [comment]
Yep that was it.  I wasn't pulling down the submodules when cloning.  So these should be the proper steps (or what worked for me):
```
git clone https://github.com/DSJAS/DSJAS.git
cd DSJAS
git submodule update --init --recursive
docker-compose build
docker-compose up
```

**Comment by ethanv2** [comment]
Not to worry. To save others the trouble, I've [changed the install instructions](https://github.com/DSJAS/DSJAS/commit/f29df8842d6e838c91cb4fda08096c758115eb4b). For future reference, we can direct people [here](https://github.com/DSJAS/DSJAS/blob/master/docs/FAQ.md#the-site-fails-to-load-it-says-something-about-require_once-failed-to-open-stream).

As far as I am aware (I do not use VSCode any more), the credentials error is related to VSCode attempting to import things like GitHub and SSH credentials into the docker container for convenience. It shouldn't affect DSJAS in any way.

Also, please don't forget to run the build script after cloning! The config files will be absent and the site will behave strangely otherwise. This only applies to downloading the site using git, and not archived releases (this happens automatically in releases).
