### ISSUE TITLE
Getting past Administrator user setup.

### ISSUE THREAD

**Issue by clstrfck-git** [DSJAS/DSJAS#2]
Filled out the text fields and press "Confirm and complete setup"
Nothing happens.

Clicking on "Skip this step" completes the setup and redirects to the "Success! You're all set up and ready to go page.

Now stuck at admin login page.
Please see attachment.

![Screenshot_2020-09-20_Admin-Login-Disabled-in-Settings](https://user-images.githubusercontent.com/67506651/93728935-76c10100-fb7f-11ea-9798-942cc795304f.png)

Admin login was checked as default in the settings if that's any help.

2 steps forward... oorah!

Thanks

**Comment by OverEngineeredCode** [comment]
I've took a look and don't think this is a bug in DSJAS and is more likely to be related to how your configuration has ended up being set up. Let's address on issue at a time.

## Final setup not working

It is likely that there was something happening, but it was taking some time to complete. After all, it is copying and creating quite a few records in the database. I would hazard a guess that something was happening, but there was no indication.

Regardless, this is a genuine issue, as a long-running operation like this should probably have some visual feedback. I will work at adding a loading indicator to the screen while it is working (should be quite trivial to do, I will get right on it).

## Log in broken

Unfortunately, because you told it to then skip, it has not written the config changes or set up a default account, so you won't be able to log in (in addition, because your config file won't yet contain the setting that enables the admin dashboard, you will probably be locked out). I'll give you some instructions on how you can go about fixing this in a second.

## Fixing it

Luckily, there is quite a simple way you can fix this. If you look in your config file, you should see a line which looks like this:

```ini
install_finalized=1
```

If you just replace the one with a zero and refresh any DSJAS pages, it should jump you back over to the admin account setup page in the installer.

You can then set all the settings as you please. *Make sure that the enable admin dashboard setting is checked!* And give it a little while to do the install before doing anything; it will get there eventually.

If there definitely still seems to be no movement, we can go from there. Give this a go first and see if it manages to fix the problem.

Thanks very much for sticking with this and helping me out fixing all these bugs. It's better to get them fixed sooner rather than later. Good luck!

**Comment by clstrfck-git** [comment]
Ya gots to break a few eggs to make an omelette.
It's gonna be sweet when it comes together.
I'll run the set up according to your instructions and let you know the outcome.
Thanks for responding so quickly.

**Comment by clstrfck-git** [comment]
Every new install attempt is preceded by dropping the 4 tables that were created by the previous install.
FYI: The tables appear within seconds of running the install.
I was monitoring phpMyAdmin.

Install was successful.
Had to skip the Admin user again.
The "install_finalized=1" line won't appear until the skip but then it's a loop.
Changed the "1" to a "0" and then kicked back to the Admin/user setup.

Looked at the users table to see if my credentials were registering.
Instead a user named "Edna Gooseberry" appears.
No data in the other tables

Screenshot:
![phpMyAdmin_EDNA_Screenshot from 2020-09-21 16-05-47](https://user-images.githubusercontent.com/67506651/93826647-efc66400-fc24-11ea-8c0d-829d462dc7dc.png)

Here's the exported sql file so you can check it out further.
[merden5_csb.sql.zip](https://github.com/DSJAS/DSJAS/files/5258398/merden5_csb.sql.zip)

Current status: stalled at Admin/User setup.

Apologies if i'm not clear but it's all greek (geek) to me.

**Comment by clstrfck-git** [comment]
UPDATE
This morning I installed the bank but went directly to "skip this step"
Edited the config.ini file: install_finalized="0"
Refreshed the page which redirected back to Admin/User setup.
Entered all the relevant info but received this error.
Actually saw this yesterday during one of the installs but forgot to report it.

![Screenshot_2020-09-22_Missing-information](https://user-images.githubusercontent.com/67506651/93883526-ed085500-fc9e-11ea-8abd-c6c07c1eb543.png)

Later...

**Comment by clstrfck-git** [comment]
Should have mentioned this earlier...
The htaccess file in the root and the admin folder had to have the "php_value" commented out otherwise there was an internal server error on the webhost.
The upload limit for filesizes has been increased on the webhost to match your values.

I'm not savvy enough to know if this might be causing an issue.

Thanks

**Comment by OverEngineeredCode** [comment]
Thanks for the extra info. Regarding the ```php_value``` directives, there shouldn't be any problems. If nothing has broken yet, then it won't break as a result of those being removed: I wouldn't worry about this specific problem.

Changing the 0 to a 1 in the config file will make all pages redirect to the respective installation page, so being taken back to the admin user setup is normal if the config file was changed.

As for the **missing info** header, make sure that you filled in all of the info boxes. Unfortunately, the final stage of the installer is only designed for accepting all the info at once right now. That error is, however, good news, because it means that the server is receiving the info and trying to do something with it - basically, the site is still working.

If you wouldn't mind trying again and making sure all the information boxes are filled in, that would be great.

**Comment by clstrfck-git** [comment]
All fields have been completed including password hint prior to seeing your post.
No progress past the Admin/User setup  so far but I'll try again later today and post an update.

**Comment by OverEngineeredCode** [comment]
The Edna account is the default "online banking" account set up for you. It comes generated with a few bank accounts and extra stuff. The default password is "hunter2", if you want to try logging in.

I will keep looking and see if I can find a reason why the final stage is broken. If possible, would you be able to post the server error logs so I can check if something is causing an error on your end. Thanks

**Comment by OverEngineeredCode** [comment]
I've looked at the code from every angle I can see and I can't see any way that the "information missing" error should arrive unless some of the info that is needed wasn't sent. So, either the browser/JS isn't sending the info properly or something has gone horribly wrong on the server. Either way, the logs will be a huge help in letting me find out what is specifically wrong with it.

**Comment by clstrfck-git** [comment]
I will loook for server and browser clonsole logs.
Both Chrome and Firefox don't handle requests correctly with all the security enhancements.
I use both so that when one fails the other might work.
Not the case so far with the bank unfortunately.
I'll update you after I've checked out the webhost server and browser consoles.

**Comment by clstrfck-git** [comment]
> I've looked at the code from every angle I can see and I can't see any way that the "information missing" error should arrive unless some of the info that is needed wasn't sent. So, either the browser/JS isn't sending the info properly or something has gone horribly wrong on the server. Either way, the logs will be a huge help in letting me find out what is specifically wrong with

Vivaldi (Chromium) browser console log:
[DSJAS_Admin-User-Setup-Attempt.log](https://github.com/DSJAS/DSJAS/files/5264232/DSJAS_Admin-User-Setup-Attempt.log)

Edited the config.ini file: install_finalized="0".

Redirected back to Admin/User setup.
Entered "edna's" credentials into the text fields and clicked "Confirm and complete setup"
Identical error as above.
No missing info header though.

Off to look for server logs.

**Comment by clstrfck-git** [comment]
> I've looked at the code from every angle I can see and I can't see any way that the "information missing" error should arrive unless some of the info that is needed wasn't sent. So, either the browser/JS isn't sending the info properly or something has gone horribly wrong on the server. Either way, the logs will be a huge help in letting me find out what is specifically wrong with it.

Sorry to report there aren't any logs available from the web host.
If there's something specific you would like to check, I could try opening a support ticket with them but wiat time is unknown.

**Comment by OverEngineeredCode** [comment]
Aha, those logs show the problem. If you look at the top line, you can see that there was an HTTP 500 error, which means that there was a PHP fatal error on the server when it tried to save the settings.

I will investigate and see if I can find the source of the problem. Thanks for the help so far, I will find the source of this problem.

**Comment by clstrfck-git** [comment]
Db credentials aren't a worry.
I'm using tmp names.
Creating a new db is NP

The last install files were deleted off the server in prep for antcitpated re-installs.
I'll run the install and send the cfg when it completes to the Adim/User page.

**Comment by clstrfck-git** [comment]
> Aha, those logs show the problem. If you look at the top line, you can see that there was an HTTP 500 error, which means that there was a PHP fatal error on the server when it tried to save the settings. Don't worry about the server logs; I can manage without them.
> 
> If you could, though, the contents of your configuration file would be really helpful. Obviously, change your database credentials to something generic.
> 
> I will investigate and see if I can find the source of the error from here. Thanks for the help so far, I will find the source of this problem.

Config #1 after installing on the initial Admin/User setup.
[Config_01.zip](https://github.com/DSJAS/DSJAS/files/5267471/Config_01.zip)

Config #2 after "Skipping this step" generates the complete ini.
Edited with the 1 to 0.
[Config_02.zip](https://github.com/DSJAS/DSJAS/files/5267472/Config_02.zip)

Let me know if you need actual credentials.
As mentioned the bank credentials are temporary and easily replaced.

The error 500 is never a good ting.
Call technical suppoat.

**Comment by OverEngineeredCode** [comment]
I'm having some difficulty finding the issue, and so is everybody else I've asked to take a look at my code/the config you sent. So, I'm stumped!

I'll take a last look at it and try one last time to root out the problem. If I really can't find the problem, I'll send you some SQL commands and modifications to the config file that will do the same thing as the final stage.

If I can't find *anything* at all that could cause this problem, I will have to conclude that it is something to do with your host's specific setup and write this off as an edge case. Sorry about that. Hopefully, the rest of the program will run a bit smoother for you.

On the bright side, my investigations have lead to several performance and design improvements, so I did at least manage to fix *something* ¯\_(ツ)_/¯

Thanks for your patience; I'll get back to you once I've done my final check over.

**Comment by clstrfck-git** [comment]
FYI: The free webhost is Freehostia and it's the first time using them.
Upgrading removes some of the more desirable features like bing allowed more than 1 db.
Free does come at a price.

This has been a grand experiment on many levels.
I'm not ready to cave on using the DSJAS package.
My next direction could be trying another free host or create a droplet on DO which would give me complete control.

I will keep you aprised of my journey with your web app.
Especially if there are any unusual issues.

It's going to be kisk ass.

Thanks

**Comment by OverEngineeredCode** [comment]
Thanks for all the help and I hope that you manage to get on fine with whatever you try next. Best of luck with DigitalOcean - hopefully that will work a little better.

If you do wish to stick with the current host, however, here's what you need to skip the install:

## Skipping the last stage of the installer

First, overwrite your config file with the following, replacing any values you wish with custom ones (you can change most of them in the admin panel anyway).

```ini
[setup]
install_finalized="1"
installed="1"
owner_verified="1"
database_installed="1"
[database]
running_without_database="0"
server_hostname="localhost"
database_name="<database-name>"
username="<database-user>"
password="<database-password>"
[customization]
bank_name="Dave Smith &amp; Johnson"
bank_domain="djsmith.bank"
[settings]
allow_access_to_admin="1"
```

Then, use the PHPMyAdmin SQL console to add a *siteUser*. You can create the default one with the following SQL:

```sql
INSERT INTO `siteusers` (`user_id`, `username`, `real_name`, `password_hash`, `password_hint`, `email`, `date_of_registration`, `account_enabled`, `new_account`) VALUES
(1, 'admin', 'user', '$2y$10$7XxUcG15dzrmzjqSaHAfsuvP26gvlH6WxXaKWctoi.J.pjhBbErPG', 'DSJAS1234', 'admin@localhost.local', '2020-07-03 16:15:09', 1, 0);
```

The username and password for this user are documented [here](https://github.com/DSJAS/DSJAS/blob/master/docs/docker/Default%20credentials.md)

---

I'm going to go ahead and close this issue now. Good luck with whatever you try next. If you have any more issues, don't be afraid to open another bug on the issue tracker or just reply to this issue if it is the same problem.

Thanks!

**Comment by clstrfck-git** [comment]
Thanks for the tutorial.
I've signed up with another free host but if it doesn't pan out I'll return to the previous host and try your code snippets.
Thanks for all your efforts.
Truly appreciated.

**Comment by OverEngineeredCode** [comment]
Since this issue was closed, the true cause of the issue has been discovered.

A technical issue in the installer was creating the site users table with incorrect capitalization. This made the rest of the program break when sending queries which related to the site users table.

The commit which fixed this issue has been referenced above.
