### ISSUE TITLE
"Unable to open file" on linux server, 

### ISSUE THREAD

**Issue by JEREDEK** [DSJAS/DSJAS#43]

**Comment by JEREDEK** [comment]
I hosted a DSJAS server on a debian web server using apache and php, but when i try to connect, all i see is an "Unable to open file!" error. What could cause this?

**Comment by ethanv2** [comment]
Please attach a screenshot of the error in question. Is there any indication of what is causing the error? Is it from Apache, PHP or DSJAS itself?

**Comment by JEREDEK** [comment]
No idea. I think it may be PHP, but i really have no way of knowing.
It's literally just a blank page with the text "Unable to open file!"

**Comment by ethanv2** [comment]
Found the problem at the following source code reference:

```php
public/include/install/Utils.php
69:    $myfile = fopen($path, "w") or die("Unable to open file!");
```

I'll work on finding the problem. Thanks for the report

**Comment by JEREDEK** [comment]
I managed to re-format my server and re-installed it, now it gets to the first screen, but once I click the button to verify my ownership, nothing happens.

**Comment by ethanv2** [comment]
Is your file permissions configured so that the directory DSJAS is installed in is writable to the user your server runs as? Check what server apache is running as by starting the server then running:

```bash
ps -eo uname:20,pid,cmd | grep 'httpd'

```

The first column should be the user which owns and can write to the server directory. If this is not the case, DSJAS will fail to create the setuptoken and the installer will fail. For a quick fix, run this command with the path to the directory and "user" replaced with the user that the server runs as mentioned earlier. **Don't forget to change this!**

```bash
sudo chown -R user:user /path/to/server/
sudo chmod -R u+rwx,o=rx /path/to/server
```

Any errors of problems, let me know. If all goes to plan, try it again and see if you get a proper install screen.

**Comment by ethanv2** [comment]
That's right. Don't forget to change the user to the one you got from the first command.

**Comment by JEREDEK** [comment]
And we're back to the same error as before
![image](https://user-images.githubusercontent.com/24723767/154571250-c4a64f5e-fd8d-447b-aedd-f4dbcf99f86a.png)

**Comment by ethanv2** [comment]
The only reason that error could appear is if the token file failed to be created. Can you check the PHP error log for me? Post it here or put it in pastebin and post a link.

**Comment by JEREDEK** [comment]
The latest error i have is from an hour ago, it were permissions denied errors to securitytoken.txt

**Comment by JEREDEK** [comment]
Ok, i reset the Config.ini file and now it works perfectly!

**Comment by ethanv2** [comment]
Great! Sorry for the inconvenience. If you have any more issues, please open another issue.
