### ISSUE TITLE
Missing Config-file?

### ISSUE THREAD

**Issue by Lele0771** [DSJAS/DSJAS#5]
Hey there

I recently wanted to step up my scambaiting to an interactive bank website and found this here which is perfect. I do have some basic knowledge about programming but i ran into a little problem which i can't seem to resolve. 

There's a file missing ("public/Config.ini"), which is not here on GitHub so i assume it should be created when starting it for the first time, which it doesn't seem to do. I tried it anyway since it's "just warnings" so i gave it a shot if the rest works. Everything else worked, I could open the website itself and the database got connected too but those warnings irritate me a bit.

I use XAMPP for the website.

![warnings](https://user-images.githubusercontent.com/81775632/113347749-eb96a400-9335-11eb-88a3-1ded67b80cff.jpg)

**Comment by ethanv2** [comment]
Hey there. Would you mind sharing how you obtained a copy of DSJAS? Judging from the folder name that DSJAS is in, it appears that you downloaded a copy using the GitHub download feature. If so, this is fine, but usually only preferred if you want to hack the site and modify its code for development purposes. Most users will want to get a copy from the [releases page](https://github.com/DSJAS/DSJAS/releases).


If you downloaded it using Git or the GitHub download zip feature, there will be a missing config file. If you download from the releases area, you should have all the files you need (including some others that are generated by the [releases script](https://github.com/DSJAS/DSJAS/blob/master/scripts/Package.py)). If you're happy using the releases as the method to obtain the program, go ahead and delete your existing install and extract the latest release into its place. You can get a copy by scrolling down to the button reading "Assets" on the releases page, and downloading either the alpha or the beta archive (depending on which you prefer). If you have some trouble, [this](https://github.com/DSJAS/DSJAS/releases/download/0.0.2-beta/DSJAS-release-beta.zip) is the link straight to the beta download. The installer will be reset, so you *will* have to go through it again to get up and running (sorry about that).

The reason these files are not included in Git is due to the fact that they are generated by scripts when you download or package a release of the program, as they contain sensitive information that needs to be stripped. So, don't worry: that's totally normal.

Try that and tell me how you get on - or if you would like to stick with the GitHub download, write back to me and I'll tell you where to go from here to generate those files.

**Comment by Lele0771** [comment]
Thanks for your very quick response. Happens to be the case that I downloaded it with the download feature and not the releases page, dumb mistake. Haven't really worked a lot with GitHub, mostly just for code inspiration. 
I downloaded the beta now and it worked perfectly after the usual configs. The reset wasn't really a big deal as I didn't really change anything yet so i had it working pretty fast. 

Thanks for taking your time and clearing everything up
Now it's time to get more familiar with this new tool and call some scammers 👌

**Comment by ethanv2** [comment]
Great news!

For your future records (and to aid in helping you get to know the program), I wrote up a whole load of guides and instructions in the documentation, that you can get at https://github.com/DSJAS/DSJAS/tree/master/docs.

Happy scambaiting.
