### ISSUE TITLE
Installing the development version from git gives php error in DB.php

### ISSUE THREAD

**Issue by accessiblepixel** [DSJAS/DSJAS#55]
Hi

I'm trying to install the development version (the regular build seems to work fine, but I want to make some changes, such as to be able to change the currency in the theme)

but when I'm running the development version, after installing it, the pages are blank and I get the following php error in the apache error log.

PHP Parse error: syntax error, unexpected ')', expecting '|' or variable (T_VARIABLE) in /var/www/html/include/DB.php on line 231

I've tried commenting parts of it out but had no luck so far... am I doing something wrong?

Kind regards,
Jessica

Edit: I am using Debian 11 with apache2, php 7.4 and mariadb (if that information is needed, thought it best to provide!)

**Comment by ethanv2** [comment]
Looks like commit 2288c19 pushed code that broke on PHP versions < 8.1. Try running ``git pull`` and see if it works now.

**Comment by accessiblepixel** [comment]
Alright, that's got us mostly back up and running again, except going to the Dashboard.php to view the accounts, the column that shows the available balance is broken - it causes a php exception, I think this is maybe another compatibility issue with php7.4?

`PHP Warning:  parse_ini_file(/var/www/html/admin/site/modules/config.ini): failed to open stream: No such file or directory in /var/www/html/include/Customization.php on line 104, referer: http://x/user/Dashboard.php
[PHP Fatal error:  Uncaught Error: Class 'NumberFormatter' not found in /var/www/html/include/api/theme/Dashboard.php:126\nStack trace:\n#0 /var/www/html/admin/site/UI/default/user/Dashboard.php(136): formatCurrency()\n#1 /var/www/html/include/Theme.php(180): getTheme()\n#2 /var/www/html/include/DSJAS.php(97): Theme->loadTheme()\n#3 /var/www/html/user/Dashboard.php(46): dsjas()\n#4 {main}\n  thrown in /var/www/html/include/api/theme/Dashboard.php on line 126, referer: http://x/user/Dashboard.php
`

You think I should just upgrade to php8.1? I want to see how easy it would be to make a theme or some changes. I was gonna try and build my own site but I figured that if someone's done some of the groundwork, it'd be best to try and help, then I'm not "reinventing the wheel, but worse!" :)

One of the things i wanted to see about adding was a way to change the currency, given that scams these days are truly international. Thanks for your work on this so far and for putting this out there for anyone to use, I really appreciate it (kinda sick of reinventing the wheel badly by myself :p)

Kind regards,
Jessica

**Comment by ethanv2** [comment]
Those two errors should be easy to fix.

For the first warning, just create a file at the path in brackets (run ``touch /var/www/html/admin/site/modules/config.ini``). The error should just disappear.

For the second one, you will need to edit your php.ini file. This is usually located at ``/etc/php/php.ini``. There are a few modules that we need to be loaded. Search through the file for the following lines:

```ini
extension=php_intl.so
extension=php_mysqli
extension=php_zip.so
extension=php_fileinfo.so
```

For each one, remove the semicolon from the start of the line. If there is no semicolon there, you may need to install the extensions, but just try this for now. If you can't find lines that match, try removing the ".so" from the end of the line and the "php_" from the start of the file. When you did all of them, restart your web server and try again.

By the way, the error you are having is actually because DSJAS is trying to localize currency for your computer's settings (the php_intl module is for "internationalization"). It just defaults to your computer's language, but I think there is a way to change it in php. Good luck with any efforts in that regard.

**Comment by accessiblepixel** [comment]
You're a star! ⭐ That's got the new version up and running :)

I had to ``apt-get install php74-zip php74-intl php74-fileinfo`` as well as enabling them in the php.ini file with something similar to what you put
extension=zip (for example) in the /etc/php/7.4/apache2/php.ini file in my case, but your instructions were easy enough to follow for me :) and that got me back up and running.

I'll have a play and see if I can get currencies to change and whatnot. Do you happen to have a guide where to start on modifying the themes, somewhere available? :)

Kind regards,
Jessica

**Comment by ethanv2** [comment]
You might find https://github.com/DSJAS/DSJAS/tree/master/docs/themes interesting. The ``spec`` folder has the specification for the layout of all the files, which should help you find things. The ``api`` folder is useful if you want to script things. Other than that, you can do anything that PHP lets you do.

I'm going to close this issue now to keep by inbox clear. Good luck tinkering.
