### ISSUE TITLE
Continue to verification does nothing

### ISSUE THREAD

**Issue by ejv2** [DSJAS/DSJAS#56]
### Discussed in https://github.com/DSJAS/DSJAS/discussions/47

<div type='discussions-op-text'>

<sup>Originally posted by **NovaDorium** May  9, 2022</sup>
I am using XAMPP and the setup went well until the install webpage where it tells me to copy the code and then continue to verification, problem is if I click continue, nothing happens. 
Even if I change the localhost directory to verification.php, it just brings me back to install.php
Is there something I'm missing?</div>

Please post here for further discussion on possible fixes for this issue. Thanks.

**Comment by mickcott** [comment]
OK, have done some work on this. My original problem also included permissions on Config.ini which needs to owned by daemon. I managed to bypass verification by modding Config and Utils files. That gets me to the DB creation part which gives an error "mysqli_connect(): (HY000/1045): Access denied for user 'user'@'localhost' (using password: YES)" during DB test phase. I suspect that this may be due to password hashing, or lack of it, after filling out the DB form. Even creating the DB manually, mysqli_connect() fails using both plain and hashed passwords when parsed in the php. Hope this helps.

**Comment by ethanv2** [comment]
I suppose it is worth asking if your password is definitely correct, the account uses SQL's default authentication and that the user is allowed to log in from all hosts. This is all configured on the database side.

**Comment by mickcott** [comment]
Password was tested both unencrypted and encrypted. Visited phpmyadmin to check users and privileges. Got rid of the ANY users and set my user account to be from localhost only and temporarily no passwd. That got me through to the final bit - create the DB admin, but cannot do that as all the mysql request subsequently want me to have a password! (Quite right, what?!) so definitely moving in the right direction but really this is all just turning out to be hacks to get stuff created.

**Comment by ethanv2** [comment]
I have been reading the PHP 8 backward compatibility breaks, and it seems that these few may be problematic in particular (screenshot attached).
![screenshot-220911-1412-56](https://user-images.githubusercontent.com/45273541/189529673-e3be19dd-f867-41a0-8655-04e5d8c54054.png)

Previously, database failures just logged a warning. I added a try-catch block to save us from this, but it does not seem to always be 100% reliable. I will keep trying to find the root cause, but this does seem like it is being mainly caused by a combination of PHP changes and default configurations of the SQL server.

**Comment by Garycompton** [comment]
I am having a similar problem.  I go through all the steps up to adding bank data.  When I add bank data to hcdocs and enter localhost, I get a page with "INDEX OF/ " at the top and a list of 12 files and folders. e.g.  Code_of_Conduct.md;  Contributing.md, etc.   The last one is a Scripts folder.

**Comment by ethanv2** [comment]
@Garycompton That will be because you set your server root to the project root, not the public directory. You want your WWW-root to point to that subdirectory, as it contains all the PHP source files.

**Comment by Garycompton** [comment]
Thanks for the reply and pardon my ignorance, what are the project root and the public directory, and how do I change from one to the other?

**Comment by ethanv2** [comment]
@Garycompton When you downloaded DSJAS, all the files were placed in a single directory (folder on windows). This is not where the web server should be serving out of. There is another folder inside of there simply with the name "public" which you should use instead. For how to change from one to the other, you should search for how to change the server root of whatever webserver you are using.

**Comment by ejv2** [comment]
Hi @Garycompton, did you get any further with this issue? I am trying to clear by backlog a little bit. If you've got everything working, I mark this issue as closed for you.

**Comment by Garycompton** [comment]
Thanks for the response.  I never could make it work. I have given up and
moved on mop

**Comment by ejv2** [comment]
Sorry to hear that. If you ever pick it up again and need some help, feel free to re-open the issue or make a new one.
