### ISSUE TITLE
Cannot Load Webpage With Latest Version

### ISSUE THREAD

**Issue by Johnnyreyman** [DSJAS/DSJAS#81]
I cannot load the latest webpage or admin portal with the latest version. I can only get the sign in page. Log attatched.
![image](https://github.com/DSJAS/DSJAS/assets/31798114/1927170e-a15b-47d7-b4bc-b2248cd35f63)

**Comment by ejv2** [comment]
Did you build the docker container yourself? If so, please [pull submodules](https://github.com/DSJAS/DSJAS/discussions/74#discussioncomment-6890065).

**Comment by brianbigsommersIsFake** [comment]
@ejv2 I'm running into the same problem mentioned above. I had built the application following the Docker based instructions: 
https://github.com/DSJAS/DSJAS/blob/master/docs/docker/DSJAS%20docker%20support.md

Most pages return a 500 internal server error
![image](https://github.com/DSJAS/DSJAS/assets/148397976/eb24fe67-7733-4ca1-a348-79629b2a691e)

**Comment by brianbigsommersIsFake** [comment]
I've fixed this. This was the first time I've ever used Docker. I ran into the above issue and based on @ejv2 's input I wanted to make sure the submodules were installed. 
I tried running "git submodule update --init --recursive" but received an error around how Git wasn't installed.
So i installed Git and did a git init command in the root of the folder. 
I then tried running "git submodule update --init --recursive" and it would run without error but nothing would happen in regards to any dependencies being installed. 
I then manually downloaded the dependencies using : 
git clone https://github.com/gburtini/PHP-Hooks-System.git public/include/vendor/hooks
git clone https://github.com/rmccue/Requests.git public/include/vendor/requests

And then ran:
docker-compose down
docker-compose build --no-cache
docker-compose up

Which fixed this. It seems like the Docker container doesn't include Git so downloading these dependencies is a manual step, or at least was for me otherwise I'd get blank pages for most pages. 
This is all running on a new Virtual Machine so I had to enable hidden files as well to see the git folders.

**Comment by ejv2** [comment]
Hi @brianbigsommersIsFake. Thanks for sharing how you fixed this. When you ran the command to install submodules automatically, do you happen to know if git did in fact download those files? It should be the case that the submodules were cloned by that command, rather than you having to do it manually.

**Comment by brianbigsommersIsFake** [comment]
I'm not totally sure but I think yes, it did download them when I ran the manual command to download. If I recall correctly before I ran the submodule download command the submodules were empty folders. 
To reproduce what I did was: 
1: Ran through the steps here: https://github.com/DSJAS/DSJAS/blob/master/docs/docker/DSJAS%20docker%20support.md
2: Once Docker was running the container I went to Localhost and the page did not load

My environment is Windows 10 using using Vmware Workstation if that might matter

**Comment by brianbigsommersIsFake** [comment]
Also on an unrelated note thanks for making this a public repository! I'm sure its taken a lot of work to get it to the point it's at but from what I've seen so far it's pretty awesome!

**Comment by ejv2** [comment]
No problem! I can't seem to reproduce the issue with the submodules, so I might have to assume that this is an issue with your local git install (which is inconsequential anyways given that you solved it another way!).

I'm going to close this now. If @Johnnyreyman comes across any more issues, he can reopen it.
